#!/bin/bash
# CONTRIBUTION
## Author: Tom Sapletta
## Created Date: 17.04.2022
#
## CONFIG
ACTION="$@"
#[ "$ACTION" = "" ] && ACTION="status"
REPO_LIST=$(cat .github.repos)
ORG=$(cat .github.org)
USER=$(cat .github.user)
TOKEN=$(cat .github.token)
## COLORS
BLUE='\033[1;34m'
RED='\033[1;35m'
NC='\033[0m' # No Color
## START
#echo -e "${BLUE}$ACTION${NC}"
## save path to rerstart command
START=$(pwd)
## for empty param
if [ -z "$ACTION" ]
then
  # UPDATE
  ./repos.sh > .github.repos
  REPO_LIST=$(cat .github.repos)
  echo "$REPO_LIST"
else
## TODO: functions
## TODO: check function list, if exist in folder, if not do another

  [ $ACTION = "help" ] &&  sh .github/$ACTION.sh && exit 0
  [ $ACTION = "config" ] && sh .github/$ACTION.sh && exit 0
  [ $ACTION = "projects" ] &&  sh .github/$ACTION.sh > .github.projects && exit 0
  [ $ACTION = "repos" ] &&  sh .github/$ACTION.sh > .github.repos && exit 0
## TODO:
## TODO:
  for input in $REPO_LIST; do
     URL=${input//[$'\t\r\n']}
     BRANCH=${URL##*/}
     FOLDER_NAME=${BRANCH//.git}
     PROJECT_BRANCH=${URL##*/github.com/}
     URL_AUTH="https://$USER:$TOKEN@github.com/$PROJECT_BRANCH"
     ##LINE="git $ACTION"
     #echo "sh github.project $URL"
     #FOLDER_NAME=${"sh github.project $URL"}
     LINE="cd $FOLDER_NAME && git $ACTION && cd .."
     [ $ACTION = "clone" ] && LINE="git clone $URL_AUTH"
     PRINT="git $ACTION $URL"
     echo
     echo -e "${RED}$PRINT${NC}"
     [ "$URL" ] && eval "$LINE"
     cd $START
     echo
  done
fi
